In [7]:
import numpy as np
from sklearn.preprocessing import quantile_transform
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
rng = np.random.RandomState(0)
X = np.sort(rng.normal(loc=0.5, scale=0.25, size=(25, 1)), axis=0)

In [3]:
X

array([[-0.13824745],
       [ 0.25568053],
       [ 0.28647607],
       [ 0.31445874],
       [ 0.44871043],
       [ 0.4621607 ],
       [ 0.47419529],
       [ 0.53041875],
       [ 0.53601089],
       [ 0.57826693],
       [ 0.58341858],
       [ 0.6000393 ],
       [ 0.60264963],
       [ 0.61096581],
       [ 0.66340465],
       [ 0.69025943],
       [ 0.71610905],
       [ 0.7375221 ],
       [ 0.7446845 ],
       [ 0.86356838],
       [ 0.87351977],
       [ 0.94101309],
       [ 0.9668895 ],
       [ 1.0602233 ],
       [ 1.06743866]])

In [4]:
quantile_transform(X, n_quantiles=10, random_state=0)

array([[9.99999998e-08],
       [9.87187297e-02],
       [1.06436120e-01],
       [1.17546710e-01],
       [2.10174366e-01],
       [2.19454446e-01],
       [2.34986656e-01],
       [3.24436417e-01],
       [3.33333333e-01],
       [4.13607939e-01],
       [4.23394641e-01],
       [4.62578413e-01],
       [4.71122361e-01],
       [4.98342373e-01],
       [5.99865364e-01],
       [6.33903024e-01],
       [6.66666667e-01],
       [6.88731010e-01],
       [6.96111249e-01],
       [8.12806989e-01],
       [8.21603540e-01],
       [8.81264388e-01],
       [9.05160277e-01],
       [9.93194350e-01],
       [9.99999900e-01]])

In [9]:
quantile_transform(X,  n_quantiles=10, output_distribution='normal', random_state=0)

array([[-5.19933758e+00],
       [-1.29819399e+00],
       [-1.24383516e+00],
       [-1.12756244e+00],
       [-9.39187246e-01],
       [-8.02382491e-01],
       [-6.66240554e-01],
       [-5.40746702e-01],
       [-4.30727299e-01],
       [-3.15571132e-01],
       [-2.08290778e-01],
       [-1.04343969e-01],
       [-1.24750222e-07],
       [ 1.04344026e-01],
       [ 2.08290670e-01],
       [ 3.15571260e-01],
       [ 4.30727299e-01],
       [ 5.40747241e-01],
       [ 6.66240169e-01],
       [ 8.02382656e-01],
       [ 9.39187446e-01],
       [ 1.12756276e+00],
       [ 1.24383506e+00],
       [ 1.29819408e+00],
       [ 5.19933758e+00]])

In [10]:
quantile_transform(X,  n_quantiles=100, output_distribution='normal', random_state=0)

array([[-5.19933758e+00],
       [-1.64867252e+00],
       [-1.39062252e+00],
       [-1.15550432e+00],
       [-9.64220762e-01],
       [-8.12177743e-01],
       [-6.74014382e-01],
       [-5.48119196e-01],
       [-4.30727299e-01],
       [-3.18427424e-01],
       [-2.10273979e-01],
       [-1.04656192e-01],
       [-1.86083806e-08],
       [ 1.04656219e-01],
       [ 2.10273960e-01],
       [ 3.18427434e-01],
       [ 4.30727299e-01],
       [ 5.48119232e-01],
       [ 6.74014317e-01],
       [ 8.12177774e-01],
       [ 9.64220758e-01],
       [ 1.15550436e+00],
       [ 1.39062246e+00],
       [ 1.64867255e+00],
       [ 5.19933758e+00]])